package main

import "meso/api/models"

// muscleCatalog is the muscle lookup: every muscle a movement can tag, grouped by
// region. region drives coarse filtering ("posterior chain") and a future body
// map. Sourced from the anatomy references in ~/shart/fitness.
var muscleCatalog = []models.Muscle{
	{Name: "chest", Region: "anterior"},
	{Name: "front_delts", Region: "anterior"},
	{Name: "quads", Region: "anterior"},
	{Name: "hip_flexors", Region: "anterior"},
	{Name: "abs", Region: "core"},
	{Name: "obliques", Region: "core"},
	{Name: "lats", Region: "posterior"},
	{Name: "upper_back", Region: "posterior"},
	{Name: "lower_back", Region: "posterior"},
	{Name: "traps", Region: "posterior"},
	{Name: "rear_delts", Region: "posterior"},
	{Name: "glutes", Region: "posterior"},
	{Name: "hamstrings", Region: "posterior"},
	{Name: "calves", Region: "posterior"},
	{Name: "shoulders", Region: "shoulders"},
	{Name: "side_delts", Region: "shoulders"},
	{Name: "biceps", Region: "arms"},
	{Name: "triceps", Region: "arms"},
	{Name: "forearms", Region: "arms"},
	{Name: "adductors", Region: "legs"},
	{Name: "abductors", Region: "legs"},
	{Name: "neck", Region: "other"},
}

// primary/secondary build muscle tags concisely for the catalog below.
func primary(name string) models.MovementMuscleInput {
	return models.MovementMuscleInput{Muscle: name, Role: "primary"}
}
func secondary(name string) models.MovementMuscleInput {
	return models.MovementMuscleInput{Muscle: name, Role: "secondary"}
}
func ptr[T any](v T) *T { return &v }

// baselineMovements is the initial library the app ships with, so it isn't empty
// on first boot. A curated set across all three kinds (exercise/stretch/yoga_pose)
// grounded in the transcribed workouts and plans in ~/shart/fitness. The richer
// full import (every ppl sheet, the research plans' named sessions) is the
// CLI-driven pass described in the design's Migration & Seed section.
var baselineMovements = []models.MovementCreate{
	{
		Name:         "Barbell Deadlift",
		MovementKind: "exercise",
		Tags:         []string{"strength", "posterior-chain", "hinge", "compound"},
		Equipment:    []string{"barbell"},
		HowTo:        "Set up with the bar over mid-foot, hip-width stance. Hinge at the hips with a flat back, grip just outside the knees. Brace, then drive through the floor and stand tall, keeping the bar close to the body.",
		FormCues:     "Flat back, brace before the pull, bar drags up the shins, lock out with the hips — not the lower back.",
		CommonFaults: "Rounding the lower back, letting the bar drift forward, hyperextending at lockout, hips shooting up before the chest.",
		DefaultSets:  ptr(3),
		DefaultReps:  ptr("4–6"),
		Muscles:      []models.MovementMuscleInput{primary("hamstrings"), primary("glutes"), secondary("lower_back"), secondary("quads"), secondary("forearms")},
		SourceName:   ptr("ppl/pull-1"),
	},
	{
		Name:         "Barbell Squat",
		MovementKind: "exercise",
		Tags:         []string{"strength", "legs", "squat", "compound"},
		Equipment:    []string{"barbell", "rack"},
		HowTo:        "Bar on the upper back, shoulder-width stance, toes slightly out. Brace and descend by sitting back and down until the hips break parallel, then drive up through mid-foot.",
		FormCues:     "Chest up, knees track over toes, weight mid-foot, brace hard on the way down.",
		CommonFaults: "Knees caving in, heels lifting, chest dropping forward, cutting depth short.",
		DefaultSets:  ptr(3),
		DefaultReps:  ptr("4–6"),
		Muscles:      []models.MovementMuscleInput{primary("quads"), primary("glutes"), secondary("hamstrings"), secondary("lower_back")},
		SourceName:   ptr("ppl/legs"),
	},
	{
		Name:         "Flat Barbell Bench Press",
		MovementKind: "exercise",
		Tags:         []string{"strength", "push", "compound"},
		Equipment:    []string{"barbell", "bench"},
		HowTo:        "Lie on the bench, eyes under the bar, shoulder blades pinched and down. Grip just outside shoulder width, lower the bar to the lower chest, then press back up over the shoulders.",
		FormCues:     "Retract the shoulder blades, tuck the elbows ~45°, bar touches the lower chest, drive the feet into the floor.",
		CommonFaults: "Flaring the elbows wide, bouncing the bar off the chest, losing the shoulder-blade set, uneven lockout.",
		DefaultSets:  ptr(3),
		DefaultReps:  ptr("4–6"),
		Muscles:      []models.MovementMuscleInput{primary("chest"), secondary("triceps"), secondary("front_delts")},
		SourceName:   ptr("ppl/push-1"),
	},
	{
		Name:         "Standing Military Press",
		MovementKind: "exercise",
		Tags:         []string{"strength", "push", "overhead"},
		Equipment:    []string{"barbell"},
		HowTo:        "Bar racked at the front delts, hip-width stance, glutes and abs braced. Press straight overhead, moving the head slightly back then through, and lock out with the bar over the mid-foot.",
		FormCues:     "Squeeze the glutes, ribs down, press in a straight line, finish with the biceps by the ears.",
		CommonFaults: "Leaning back and turning it into an incline press, pressing around the face, flaring the ribs.",
		DefaultSets:  ptr(2),
		DefaultReps:  ptr("4–6"),
		Muscles:      []models.MovementMuscleInput{primary("shoulders"), primary("front_delts"), secondary("triceps")},
		SourceName:   ptr("ppl/push-1"),
	},
	{
		Name:         "Barbell Row",
		MovementKind: "exercise",
		Tags:         []string{"strength", "pull", "compound"},
		Equipment:    []string{"barbell"},
		HowTo:        "Hinge to ~45°, flat back, bar hanging at arm's length. Pull the bar to the lower ribs by driving the elbows back, then lower under control.",
		FormCues:     "Flat back held throughout, lead with the elbows, squeeze the shoulder blades at the top.",
		CommonFaults: "Standing up to heave the weight, rounding the back, using momentum instead of the lats.",
		DefaultSets:  ptr(3),
		DefaultReps:  ptr("4–6"),
		Muscles:      []models.MovementMuscleInput{primary("lats"), primary("upper_back"), secondary("biceps"), secondary("rear_delts")},
		SourceName:   ptr("ppl/pull-1"),
	},
	{
		Name:         "Wide Grip Pull-up",
		MovementKind: "exercise",
		Tags:         []string{"strength", "pull", "bodyweight"},
		Equipment:    []string{"pull-up-bar"},
		HowTo:        "Hang from a wide overhand grip, shoulders active. Pull the chest toward the bar by driving the elbows down and back, then lower to a full hang.",
		FormCues:     "Start from active shoulders, lead with the chest, full range top and bottom.",
		CommonFaults: "Half reps, kipping/swinging, shrugging the shoulders instead of depressing them.",
		DefaultSets:  ptr(3),
		DefaultReps:  ptr("4–6"),
		Muscles:      []models.MovementMuscleInput{primary("lats"), secondary("upper_back"), secondary("biceps")},
		SourceName:   ptr("ppl/pull-1"),
	},
	{
		Name:         "Bulgarian Split Squat",
		MovementKind: "exercise",
		Tags:         []string{"strength", "legs", "unilateral"},
		Equipment:    []string{"dumbbell", "bench"},
		HowTo:        "Rear foot elevated on a bench, front foot planted a stride ahead. Lower straight down until the front thigh is parallel, then drive up through the front heel.",
		FormCues:     "Torso tall, front knee tracks over the foot, weight in the front heel.",
		CommonFaults: "Front knee caving in, pushing off the back foot, too short a stance.",
		DefaultSets:  ptr(3),
		DefaultReps:  ptr("6–8"),
		Muscles:      []models.MovementMuscleInput{primary("quads"), primary("glutes"), secondary("hamstrings")},
		SourceName:   ptr("ppl/legs"),
	},
	{
		Name:         "Standing Calf Raise",
		MovementKind: "exercise",
		Tags:         []string{"strength", "legs", "isolation"},
		Equipment:    []string{"dumbbell"},
		HowTo:        "Stand tall, balls of the feet on a slight rise. Rise onto the toes as high as possible, pause, then lower the heels below the platform for a full stretch.",
		FormCues:     "Full range top and bottom, pause at the top, control the descent.",
		CommonFaults: "Bouncing, cutting the range short, rushing the reps.",
		DefaultSets:  ptr(3),
		DefaultReps:  ptr("8–10"),
		Muscles:      []models.MovementMuscleInput{primary("calves")},
		SourceName:   ptr("ppl/legs"),
	},
	{
		Name:         "Dumbbell Lateral Raise",
		MovementKind: "exercise",
		Tags:         []string{"shoulders", "isolation"},
		Equipment:    []string{"dumbbell"},
		HowTo:        "Stand with dumbbells at the sides, a slight bend in the elbows. Raise the arms out to shoulder height leading with the elbows, then lower slowly.",
		FormCues:     "Lead with the elbows, slight forward tilt, no shrugging.",
		CommonFaults: "Using momentum, shrugging the traps, raising above shoulder height.",
		DefaultSets:  ptr(2),
		DefaultReps:  ptr("8–10"),
		Muscles:      []models.MovementMuscleInput{primary("side_delts"), secondary("shoulders")},
		SourceName:   ptr("ppl/push-1"),
	},
	{
		Name:         "Prisoner Squat",
		MovementKind: "exercise",
		Tags:         []string{"bodyweight", "legs", "warmup", "apartment"},
		Equipment:    []string{"bodyweight"},
		HowTo:        "Hands laced behind the head, elbows wide. Squat to depth keeping the chest up, then stand tall.",
		FormCues:     "Elbows stay back, knees track over the toes, weight mid-foot.",
		CommonFaults: "Elbows collapsing forward, chest dropping, heels lifting.",
		DefaultSets:  ptr(3),
		DefaultReps:  ptr("12–15"),
		Muscles:      []models.MovementMuscleInput{primary("quads"), secondary("glutes")},
		SourceName:   ptr("flexibility-moves"),
	},
	{
		Name:         "Push-up",
		MovementKind: "exercise",
		Tags:         []string{"bodyweight", "push", "apartment"},
		Equipment:    []string{"bodyweight"},
		HowTo:        "Hands under the shoulders, body in a straight line from head to heels. Lower until the chest nearly touches the floor, then press back up.",
		FormCues:     "Brace the abs and glutes, elbows ~45°, full lockout at the top.",
		CommonFaults: "Sagging hips, flaring the elbows, partial range.",
		DefaultSets:  ptr(3),
		DefaultReps:  ptr("AMRAP"),
		Muscles:      []models.MovementMuscleInput{primary("chest"), secondary("triceps"), secondary("abs")},
		SourceName:   ptr("general-workouts/apartment-1"),
	},
	{
		Name:         "Cable Crunch",
		MovementKind: "exercise",
		Tags:         []string{"core", "isolation"},
		Equipment:    []string{"cable"},
		HowTo:        "Kneel below a rope attachment, hands at the head. Crunch down by flexing the spine, bringing the elbows toward the thighs, then return under control.",
		FormCues:     "Crunch with the abs, not the hips; keep the hips fixed.",
		CommonFaults: "Turning it into a hip hinge, using the arms to pull, going too fast.",
		DefaultSets:  ptr(3),
		DefaultReps:  ptr("8–10"),
		Muscles:      []models.MovementMuscleInput{primary("abs"), secondary("obliques")},
		SourceName:   ptr("ppl/push-1"),
	},
	{
		Name:               "Couch Stretch",
		MovementKind:       "stretch",
		Tags:               []string{"mobility", "hip-opener", "desk-counter"},
		Equipment:          []string{"mat"},
		HowTo:              "Rear knee against a wall or couch with the shin vertical, front foot planted ahead. Tuck the pelvis and raise the torso upright to stretch the rear hip flexor and quad.",
		FormCues:           "Squeeze the rear glute, tuck the tailbone, keep the ribs down.",
		CommonFaults:       "Arching the lower back to fake more range, letting the front knee cave.",
		DefaultHoldSeconds: ptr(60),
		MeasurableROM:      true,
		Muscles:            []models.MovementMuscleInput{primary("hip_flexors"), secondary("quads")},
		SourceName:         ptr("flexibility-moves"),
	},
	{
		Name:               "Standing Hamstring Stretch",
		MovementKind:       "stretch",
		Tags:               []string{"mobility", "posterior-chain", "toe-reach"},
		Equipment:          []string{"bodyweight"},
		HowTo:              "Feet together, hinge at the hips with a long spine and reach toward the toes. Let the stretch build in the hamstrings; don't bounce.",
		FormCues:           "Hinge from the hips, long spine, breathe into the stretch.",
		CommonFaults:       "Rounding hard through the back, bouncing, bending the knees to reach further.",
		DefaultHoldSeconds: ptr(30),
		MeasurableROM:      true,
		Muscles:            []models.MovementMuscleInput{primary("hamstrings"), secondary("lower_back")},
		SourceName:         ptr("goals: toe reach"),
	},
	{
		Name:               "Knee-to-Wall Ankle Stretch",
		MovementKind:       "stretch",
		Tags:               []string{"mobility", "ankle", "measurable"},
		Equipment:          []string{"bodyweight"},
		HowTo:              "Face a wall in a half-kneel, front foot a few inches back. Drive the knee forward over the toes to touch the wall without lifting the heel; back the foot up until it's the max distance you can still touch.",
		FormCues:           "Heel stays down, knee tracks over the second toe.",
		CommonFaults:       "Letting the heel lift, collapsing the arch inward.",
		DefaultHoldSeconds: ptr(20),
		MeasurableROM:      true,
		Muscles:            []models.MovementMuscleInput{primary("calves")},
		SourceName:         ptr("goals: knee-to-wall"),
	},
	{
		Name:         "Leg Swings",
		MovementKind: "stretch",
		Tags:         []string{"mobility", "dynamic", "warmup"},
		Equipment:    []string{"bodyweight"},
		HowTo:        "Hold a support and swing one leg forward and back through a comfortable range, gradually increasing the arc. Keep the torso upright.",
		FormCues:     "Controlled swing, upright torso, build the range gradually.",
		CommonFaults: "Yanking the leg past its range, twisting the torso.",
		DefaultReps:  ptr("10 each side"),
		Muscles:      []models.MovementMuscleInput{primary("hip_flexors"), secondary("hamstrings")},
		SourceName:   ptr("flexibility-moves"),
	},
	{
		Name:               "Pigeon Pose",
		MovementKind:       "yoga_pose",
		Tags:               []string{"mobility", "hip-opener", "cooldown"},
		Equipment:          []string{"mat"},
		HowTo:              "From all fours, bring one shin forward under the torso and extend the other leg straight back. Square the hips and fold forward over the front shin to open the glute.",
		FormCues:           "Keep the hips square, flex the front foot, breathe into the glute.",
		CommonFaults:       "Collapsing onto one hip, letting the back foot splay, forcing the fold.",
		DefaultHoldSeconds: ptr(45),
		SanskritName:       ptr("Eka Pada Rajakapotasana"),
		Muscles:            []models.MovementMuscleInput{primary("glutes"), secondary("hip_flexors")},
		SourceName:         ptr("dance-conditioning"),
	},
	{
		Name:               "Downward-Facing Dog",
		MovementKind:       "yoga_pose",
		Tags:               []string{"mobility", "posterior-chain", "full-body"},
		Equipment:          []string{"mat"},
		HowTo:              "From all fours, tuck the toes and lift the hips up and back into an inverted V. Press the floor away, lengthen the spine, and reach the heels toward the ground.",
		FormCues:           "Long spine over flat heels, press through the hands, hips high.",
		CommonFaults:       "Rounding the upper back, locking the knees hard, shoulders creeping to the ears.",
		DefaultHoldSeconds: ptr(30),
		SanskritName:       ptr("Adho Mukha Svanasana"),
		Muscles:            []models.MovementMuscleInput{primary("hamstrings"), secondary("calves"), secondary("shoulders")},
		SourceName:         ptr("dance-conditioning"),
	},
	{
		Name:               "Child's Pose",
		MovementKind:       "yoga_pose",
		Tags:               []string{"mobility", "recovery", "cooldown"},
		Equipment:          []string{"mat"},
		HowTo:              "Kneel and sit back on the heels, then fold forward, extending the arms ahead and resting the forehead on the mat.",
		FormCues:           "Let the hips sink toward the heels, relax the shoulders, breathe into the back.",
		CommonFaults:       "Tensing the shoulders, holding the breath, forcing the hips down.",
		DefaultHoldSeconds: ptr(60),
		SanskritName:       ptr("Balasana"),
		Muscles:            []models.MovementMuscleInput{primary("lower_back")},
		SourceName:         ptr("dance-conditioning"),
	},
	{
		Name:               "Cobra Pose",
		MovementKind:       "yoga_pose",
		Tags:               []string{"mobility", "thoracic", "desk-counter"},
		Equipment:          []string{"mat"},
		HowTo:              "Lie face down, hands under the shoulders. Press the chest up and forward into a gentle backbend, keeping the hips on the mat and the elbows slightly bent.",
		FormCues:           "Lead with the chest, shoulders down and back, hips grounded.",
		CommonFaults:       "Cranking the neck back, shrugging the shoulders, pushing to full arm lockout too soon.",
		DefaultHoldSeconds: ptr(20),
		SanskritName:       ptr("Bhujangasana"),
		Muscles:            []models.MovementMuscleInput{primary("lower_back"), secondary("abs")},
		SourceName:         ptr("references/thoracic-spine-mobility"),
	},
}
